### ISSUE TITLE
low level design of input/outputs

### ISSUE THREAD

**Issue by lext05** [lext05/family-finance#5]

**Comment by davidkhuu** [comment]
Going off our first draft of the MVP features. A little confused about input/output for some scenarios so I'll just lay it out and you guys can help me finish it off if I'm not doing it correctly.

**Log in**
Input: Username, password
Output: Key? (however we decide to do auth)

**Log out**
Input: ?
Output: Logout screen

**Uploading (importing) data**
Input: File (.csv, .xml)
Output: Data stored to DB. Displayed to user.

**Downloading (exporting) data**
Input: User data in DB (financial records)
Output: File (.csv, .xml?) 

**View finances via tables**
Input: User data in DB
Output: Categorized records from DB

**View finances via dashboard (probably as graphs)**
Input: User data in DB
Output: Categorized records as visual representation
